INTERFACE
SUBROUTINE CUBASEN&
 & ( KIDIA, KFDIA, KLON, KTDIA, KLEV,&
 & LDLAND,&
 & PTENH, PQENH, PGEOH, PAPH,&
 & PQHFL, PAHFS, PSSTRU, PSSTRV, PWN,&
 & PTEN, PQEN, PGEO,&
 & PUEN, PVEN,&
 & PTU, PQU, PLU, PUU, PVU , PWUBASE,&
 & KLAB, LDCUM, LDSC, KCBOT, KBOTSC,&
 & KCTOP, KDPL, PCAPE ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM) :: KTDIA
LOGICAL(KIND=JPIM) :: LDLAND(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTENH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQENH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PQHFL(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PAHFS(KLON,KLEV+1)
REAL(KIND=JPRB) :: PSSTRU(KLON)
REAL(KIND=JPRB) :: PSSTRV(KLON)
REAL(KIND=JPRB) :: PWN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEO(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PUEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PVEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PQU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PLU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PUU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PVU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PWUBASE(KLON)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KLAB(KLON,KLEV)
LOGICAL ,INTENT(INOUT) :: LDCUM(KLON)
LOGICAL ,INTENT(OUT) :: LDSC(KLON)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KCBOT(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KBOTSC(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KCTOP(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KDPL(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCAPE(KLON)
END SUBROUTINE CUBASEN
END INTERFACE
