INTERFACE
SUBROUTINE CUCTRACER&
 & ( KIDIA, KFDIA, KLON, KTDIA, KLEV, KTRAC,&
 & KTYPE, KCTOP, KCBOT, KDPL, KDTOP,&
 & LDCUM, LDDRAF, PTSPHY, PAPH,&
 & PMFU, PMFD, PUDRATE, PDDRATE,&
 & PCEN, PTENC ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KTRAC
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM) :: KTDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTYPE(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KCTOP(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KCBOT(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KDPL(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KDTOP(KLON)
LOGICAL ,INTENT(IN) :: LDCUM(KLON)
LOGICAL ,INTENT(IN) :: LDDRAF(KLON)
REAL(KIND=JPRB) ,INTENT(IN) :: PTSPHY
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PMFU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PMFD(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PUDRATE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PDDRATE(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PCEN(KLON,KLEV,KTRAC)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PTENC(KLON,KLEV,KTRAC)
END SUBROUTINE CUCTRACER
END INTERFACE
