INTERFACE
SUBROUTINE CUENTR&
 & ( KIDIA, KFDIA, KLON, KTDIA, KLEV,&
 & KK, KLWMIN, KTYPE, KCBOT, KCTOP0,&
 & LDCUM, LDWORK,&
 & PTENH, PQENH, PQSEN, PAPH, PGEOH,&
 & PMFU, PENTR,&
 & PCBASE, PDMFEN, PDMFDE ) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM) :: KTDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KK
INTEGER(KIND=JPIM),INTENT(IN) :: KLWMIN(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KTYPE(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KCBOT(KLON)
INTEGER(KIND=JPIM),INTENT(IN) :: KCTOP0(KLON)
LOGICAL ,INTENT(IN) :: LDCUM(KLON)
LOGICAL ,INTENT(IN) :: LDWORK
REAL(KIND=JPRB) ,INTENT(IN) :: PTENH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQENH(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PQSEN(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PGEOH(KLON,KLEV+1)
REAL(KIND=JPRB) ,INTENT(IN) :: PMFU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PENTR(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCBASE(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDMFEN(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDMFDE(KLON)
END SUBROUTINE CUENTR
END INTERFACE
