INTERFACE
SUBROUTINE SATUR ( KIDIA , KFDIA , KLON , KTDIA , KLEV,&
 & PAPRSF, PT , PQSAT , KFLAG) 
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMJFH , ONLY : N_VMASS
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQSAT(KLON,KLEV)
INTEGER(KIND=JPIM),INTENT(IN) :: KFLAG
END SUBROUTINE SATUR
END INTERFACE
