SUBROUTINE SU_YOETHF

USE PARKIND1  ,ONLY : JPIM     ,JPRB

USE YOETHF
USE YOMCST

IMPLICIT NONE

RVTMP2=RCPV/RCPD-1.
RHOH2O=RATM/100._JPRB
R2ES=611.21_JPRB*RD/RV
R3LES=17.502_JPRB
R3IES=22.587_JPRB
R4LES=32.19_JPRB
R4IES=-0.7_JPRB
R5LES=R3LES*(RTT-R4LES)
R5IES=R3IES*(RTT-R4IES)
R5ALVCP=R5LES*RLVTT/RCPD
R5ALSCP=R5IES*RLSTT/RCPD
RALVDCP=RLVTT/RCPD
RALSDCP=RLSTT/RCPD
RALFDCP=RLMLT/RCPD
RTWAT=RTT
RTBER=RTT-5._JPRB
RTBERCU=RTT-5.0_JPRB
RTICE=RTT-23._JPRB
RTICECU=RTT-23._JPRB
RTWAT_RTICE_R=1._JPRB/(RTWAT-RTICE)
RTWAT_RTICECU_R=1._JPRB/(RTWAT-RTICECU)

END SUBROUTINE SU_YOETHF

