MODULE YOMHOOK_IFS
  USE PARKIND1  ,ONLY : JPIM     ,JPRB
  LOGICAL::LHOOK=.FALSE.

SAVE
PUBLIC DR_HOOK

CONTAINS

SUBROUTINE DR_HOOK(CH,K1,P1)
USE PARKIND1  ,ONLY : JPIM     ,JPRB
IMPLICIT NONE
CHARACTER::CH
INTEGER(KIND=JPIM)::K1
REAL(KIND=JPRB)::P1
END SUBROUTINE DR_HOOK

END MODULE YOMHOOK_IFS
