#! /bin/tcsh -f

if ($# == 0) then
   echo "USAGE: $0 <solver>"
exit 1
endif

set integr = $1

  # select correct script for the chosen integrator
  switch ("$integr")

#  case "ros2-log3":
#  case "ros2-log5":
#  case "ros2-log6":
#  case "ros2-log10":
#  case "ros2-lin1":
#  case "ros2-lin3":
#  case "ros2-lin9":
#
#    echo "./sedsolve_ros2 "
#    ./sedsolve_ros2
#    breaksw

  case "ros3":
  case "ros3-diag":
  case "ros3-autonom":

    echo "./sedsolve_ros3 "
    ./sedsolve_ros3
    breaksw

  case "radau5":

    echo "ERROR: vectorization not possible for radau5"
    breaksw

  default:

    echo "ERROR: unknown solver"
    breaksw

  endsw

exit
