#! /bin/tcsh -f
# Author: Holger Tost, Max-Planck-Institute, Mainz, Germany, 2004
# Time-stamp: <2007-09-25 15:37:18 tost>

# this scipt automatically creates a module of the include files created
# by tracmvscav.awk 

echo " \! this file is automatically created by xscav_i - do not change \!"
echo ""
echo "   MODULE MESSY_SCAV_I_AUTO_KPP"
echo ""
echo ""
echo "   USE MESSY_SCAV_I_KPP_G_MEM,    ONLY: nspec"
echo ""
echo "     IMPLICIT NONE"
echo ""
echo "     SAVE"
echo ""
echo "     PRIVATE" 
echo ""
echo ""
echo "       INTEGER, PUBLIC :: idt_scav_NH3        = 0"
echo "       INTEGER, PUBLIC :: idt_scav_NO3mres_cs = 0"       
echo "       INTEGER, PUBLIC :: idt_scav_SO4res_cs  = 0"
echo "       INTEGER, PUBLIC :: idt_scav_nh4pres_cs = 0"
echo "       INTEGER, PUBLIC :: idt_scav_Clmres_cs  = 0" 
echo "       INTEGER, PUBLIC :: idt_scav_Hpres_cs   = 0"
echo "       PUBLIC :: STR_KPP"
echo ""
echo "   CONTAINS"
echo ""
echo "\!-------------------------------------------------------------------------"
echo "     SUBROUTINE STR_KPP(str_field_kpp)"
echo ""
echo "         IMPLICIT NONE"
echo ""
echo "         CHARACTER(LEN=*), INTENT(INOUT) :: str_field_kpp(nspec)"
echo ""
cat messy_scav_str_kpp.inc
echo ""
echo "     END SUBROUTINE STR_KPP"
echo ""
echo "\!-------------------------------------------------------------------------"
echo ""
echo "   END MODULE MESSY_SCAV_I_AUTO_KPP"

exit
