! ****************************************************************************
! this file was created automatically by xscav, do not edit
! ****************************************************************************
! messy_scav_i_kpp.f90
! ****************************************************************************
! user           = joec_pa
! creation date  = Tue Jul  3 19:35:32 CEST 2018
! iceeqnfile     = ice.eqn
! selection      = 1
! integrator     = ros3
! ****************************************************************************
! START: scav.eqn
! ****************************************************************************
! {selected reactions = (1)}
! #INLINE F95_RCONST
!   USE messy_scav_ice
!   USE messy_scav_mem
! #ENDINLINE
! #EQUATIONS
! {******** aqueous reactions from:   ice.eqn ******}
! {***** START: scav chemistry from ice.eqn *****}
! {#H1nnni}{------------------------ O -------------------------}
! {#H2nnni}{------------------------ H -------------------------}{%Ice}{@\hline}
! {#H3nnni}{------------------------ N -------------------------}{%Ice}{@\hline}
! {#H3203fi} HNO3    = HNO3_i           : {%TrIceNScScm} k_exf(KPP_HNO3); {&&}
! {#H3203bi} HNO3_i = HNO3              : {%TrIceNScScm} k_exb(KPP_HNO3); {&&}
! {#H4nnni}{------------------------ C -------------------------}{%Ice}{@\hline}
! {#H4100fi} CO2        = CO2_i    : {%TrIceScScm} 0. ; {&&}
! {***** END:   scav chemistry from ice.eqn *****}
! ****************************************************************************
! END:   scav.eqn
! ****************************************************************************

! **************************************************************** 
!                                                                  
! Generated by KPP - symbolic chemistry Kinetics PreProcessor      
!     KPP is developed at CGRER labs University of Iowa by         
!     Valeriu Damian & Adrian Sandu                                
!                                                                  
! File                 : scav_i.f90                                
! Time                 : Tue Jul  3 19:35:32 2018                  
! Working directory    : /athome/joec_pa/MESSY/messy_d2.53.0.23_dev/messy/mbm/scav/mechanism
! Equation file        : scav_i.k                                  
! Output root filename : scav_i                                    
!                                                                  
! **************************************************************** 






MODULE messy_scav_i_kpp

USE messy_scav_i_kpp_g_mem

IMPLICIT NONE

CONTAINS

! **************************************************************** 
!                                                                  
! F_VAR - function for the derivatives of variables - Agregate form
!   Parameters :                                                   
!      V         - Concentration of variable species               
!      R         - Concentration of radicals                       
!      A_VAR     - Agregate term                                   
!                                                                  
! **************************************************************** 

      SUBROUTINE F_VAR ( V, R, A_VAR )

! V - Concentration of variable species                            
      REAL(dp), DIMENSION(NVAR) :: V
! R - Concentration of radicals                                    
      REAL(dp), DIMENSION(NRAD) :: R
! A_VAR - Agregate term                                            
      REAL(dp), DIMENSION(NVAR) :: A_VAR


! Local variables                                                  
! A - rate for each equation                                       
      REAL(dp), DIMENSION(NREACT) :: A

! Computation of equation rates                                    
      A(1) = RCONST(1)*V(3)
      A(2) = RCONST(2)*V(2)
      A(3) = 0

! Aggregate function                                               
      A_VAR(1) = A(3)
      A_VAR(2) = A(1)-A(2)
      A_VAR(3) = -A(1)+A(2)
      END SUBROUTINE F_VAR

! End of F_VAR function                                            
! **************************************************************** 


! **************************************************************** 
!                                                                  
! JACVAR_SP - function for the Jacobian of Variables using sparse matrix representation
!   Parameters :                                                   
!      V         - Concentration of variable species               
!      R         - Concentration of radicals                       
!      JVS       - the Jacobian of variables                       
!                                                                  
! **************************************************************** 

      SUBROUTINE JACVAR_SP ( V, R, JVS )

! V - Concentration of variable species                            
      REAL(dp), DIMENSION(NVAR) :: V
! R - Concentration of radicals                                    
      REAL(dp), DIMENSION(NRAD) :: R
! JVS - the Jacobian of variables                                  
      REAL(dp), DIMENSION(LU_NONZERO_V+1) :: JVS


! Local variables                                                  
! NTMPB - Length of Temporary Array B                              
      INTEGER, PARAMETER :: NTMPB = 3 
! B - temporary matrix                                             
      REAL(dp), DIMENSION(NTMPB) :: B

! B(1) = dA(1)/dV(3)                                               
      B(1) = RCONST(1)
! B(2) = dA(2)/dV(2)                                               
      B(2) = RCONST(2)

! Construct the Jacobian terms from B's                            
! JVS(1) = JACVAR.FULL(1,1)                                        
      JVS(1) = 0
! JVS(2) = JACVAR.FULL(2,2)                                        
      JVS(2) = -B(2)
! JVS(3) = JACVAR.FULL(2,3)                                        
      JVS(3) = B(1)
! JVS(4) = JACVAR.FULL(3,2)                                        
      JVS(4) = B(2)
! JVS(5) = JACVAR.FULL(3,3)                                        
      JVS(5) = -B(1)
      END SUBROUTINE JACVAR_SP

! End of JACVAR_SP function                                        
! **************************************************************** 


! **************************************************************** 
!                                                                  
! JACVAR_SP_VEC - function for sparse multiplication: sparse Jacobian times vector
!   Parameters :                                                   
!      JVS       - the Jacobian of variables                       
!      UV        - user vector for variables                       
!      JUV       - Jacobian times user vector                      
!                                                                  
! **************************************************************** 

      SUBROUTINE JACVAR_SP_VEC ( JVS, UV, JUV )

! JVS - the Jacobian of variables                                  
      REAL(dp), DIMENSION(LU_NONZERO_V+1) :: JVS
! UV - user vector for variables                                   
      REAL(dp), DIMENSION(NVAR) :: UV
! JUV - Jacobian times user vector                                 
      REAL(dp), DIMENSION(NVAR) :: JUV

      JUV(1) = JVS(1)*UV(1)
      JUV(2) = JVS(2)*UV(2)+JVS(3)*UV(3)
      JUV(3) = JVS(4)*UV(2)+JVS(5)*UV(3)
      END SUBROUTINE JACVAR_SP_VEC

! End of JACVAR_SP_VEC function                                    
! **************************************************************** 


! **************************************************************** 
!                                                                  
! SPARSE_UTIL - SPARSE Utility functions                           
!   Parameters :                                                   
!                                                                  
! **************************************************************** 


      subroutine DECOMP(N,V,IER)

      USE messy_scav_i_kpp_s_mem
      IMPLICIT NONE ! mz_rs_20030728

      REAL(dp) V(LU_NONZERO_V+1), W(NSPEC) ! mz_rs_20020530: 1 added
      integer k, kk, j, jj
      integer N,IER ! mz_rs_20030728
      REAL(dp) a 

      IER = 0
      do k=1,N
        ! mz_rs_20040202: don't check if real value == 0
        ! if ( V( LU_DIAG_V(k) ) .eq. 0. ) then
        if ( ABS(V(LU_DIAG_V(k))) < TINY(a) ) then
            IER = k
            return
        end if
        do kk = LU_CROW_V(k), LU_CROW_V(k+1)-1
              W( LU_ICOL_V(kk) ) = V(kk)
        end do
        do kk = LU_CROW_V(k), LU_DIAG_V(k)-1
            j = LU_ICOL_V(kk)
            a = -W(j) / V( LU_DIAG_V(j) )
            W(j) = -a
            do jj = LU_DIAG_V(j)+1, LU_CROW_V(j+1)-1
               W( LU_ICOL_V(jj) ) = W( LU_ICOL_V(jj) ) + a*V(jj)
            end do
         end do
         do kk = LU_CROW_V(k), LU_CROW_V(k+1)-1
            V(kk) = W( LU_ICOL_V(kk) )
         end do
      end do
      end subroutine decomp
! End of SPARSE_UTIL function                                      
! **************************************************************** 


! **************************************************************** 
!                                                                  
! SOLVE - function for sparse back substitution                    
!   Parameters :                                                   
!      JVS       - the Jacobian of variables                       
!      X         - vector for variables                            
!                                                                  
! **************************************************************** 

      SUBROUTINE SOLVE ( JVS, X )

      USE messy_scav_i_kpp_s_mem
      IMPLICIT NONE
! JVS - the Jacobian of variables                                  
      REAL(dp), DIMENSION(LU_NONZERO_V+1) :: JVS
! X - vector for variables                                         
      REAL(dp), DIMENSION(NVAR) :: X

      X(3) = X(3)-JVS(4)*X(2)
      X(3) = X(3)/JVS(5)
      X(2) = (X(2)-JVS(3)*X(3))/(JVS(2))
      X(1) = X(1)/JVS(1)
      END SUBROUTINE SOLVE

! End of SOLVE function                                            
! **************************************************************** 


! **************************************************************** 
!                                                                  
! INITVAL - function to update initial concentrations              
!   Parameters :                                                   
!                                                                  
! **************************************************************** 

      SUBROUTINE INITVAL ( )


      INTEGER :: i
      REAL(dp) :: x

      x = (0.)*CFACTOR
      do i = 1, NVAR
        VAR(i) = x
      end do

      x = (0.)*CFACTOR
      do i = 1, NRAD
        RAD(i) = x
      end do

      x = (0.)*CFACTOR
      do i = 1, NFIX
        FIX(i) = x
      end do


      do i = 1, NSPEC
        C_DEFAULT(i) = C(i)
      end do

! Set dummy default value for RCONST to avoid that the             
! non temperature-dependent elements remain undefined              
      RCONST(:)=-999.

! User defined initialisations                                     

        STEPMIN=0.0001
        STEPMAX=60.
        ISNOTAUTONOM=1
        STEPSTART=STEPMIN

        ! from ros3.k:
        ! STEPMIN=0.0001
        STEPMIN=1.E-37 ! mz_ak_20040707
        STEPMAX=4800.
        STEPSTART=STEPMIN

! End user defined initialisations                                 

      END SUBROUTINE INITVAL

! End of INITVAL function                                          
! **************************************************************** 


! **************************************************************** 
!                                                                  
! UPDATE_SUN - update SUN light using TIME                         
!   Parameters :                                                   
!                                                                  
! **************************************************************** 

      SUBROUTINE UPDATE_SUN()

!      INCLUDE 'scav_i.h'
      ! USE messy_scav_i_kpp_g_mem ! mz_rs_20040202: gdata is already USEd in the whole module
      IMPLICIT NONE !mz_rs_20030728

      REAL(dp) SunRise, SunSet
      REAL(dp) Thour, Tlocal, Ttmp 
   
      SunRise = 4.5
      SunSet  = 19.5
      Thour = TIME/3600.
      Tlocal = Thour - (int(Thour)/24)*24

      IF ((Tlocal.GE.SunRise).AND.(Tlocal.LE.SunSet)) THEN
        Ttmp = (2.0*Tlocal-SunRise-SunSet)/(SunSet-SunRise)
        IF (Ttmp.GT.0) THEN
          Ttmp =  Ttmp*Ttmp
        ELSE
          Ttmp = -Ttmp*Ttmp
        END IF
        SUN = ( 1.0 + COS(PI*Ttmp) )/2.0 
      ELSE
        SUN=0.0
      END IF

      END SUBROUTINE UPDATE_SUN

! End of UPDATE_SUN function                                       
! **************************************************************** 


! **************************************************************** 
!                                                                  
! UPDATE_RCONST - function to update rate constants                
!   Parameters :                                                   
!                                                                  
! **************************************************************** 

      SUBROUTINE UPDATE_RCONST ( )



! User defined functions                                           

  USE messy_scav_ice
  USE messy_scav_mem

      RCONST(1) = (k_exf(KPP_HNO3))
      RCONST(2) = (k_exb(KPP_HNO3))
      END SUBROUTINE UPDATE_RCONST

! End of UPDATE_RCONST function                                    
! **************************************************************** 


! **************************************************************** 
!                                                                  
! UPDATE_PHOTO - function to update photolitical rate constants    
!   Parameters :                                                   
!                                                                  
! **************************************************************** 

      SUBROUTINE UPDATE_PHOTO ( )



! User defined functions                                           

  USE messy_scav_ice
  USE messy_scav_mem

      END SUBROUTINE UPDATE_PHOTO

! End of UPDATE_PHOTO function                                     
! **************************************************************** 


! **************************************************************** 
!                                                                  
! INTEGRATE - Integrator routine                                   
!   Parameters :                                                   
!      TIN       - Start Time for Integration                      
!      TOUT      - End Time for Integration                        
!                                                                  
! **************************************************************** 

      SUBROUTINE INTEGRATE( TIN, TOUT )

      USE messy_scav_i_kpp_g_mem

      IMPLICIT NONE

! TIN - Start Time
      REAL(dp) TIN
! TOUT - End Time
      REAL(dp) TOUT

      !INTEGER    INFO(5) ! mz_ak_20060831 use from GDATA instead

      INFO(1) = 1 - ISNOTAUTONOM

        CALL ROS3(NVAR,TIN,TOUT,STEPMIN,STEPMAX, &
                         STEPSTART,VAR,ATOL,RTOL, &
                         Info)

      END SUBROUTINE INTEGRATE

      
      SUBROUTINE ROS3(N,T,Tnext,Hmin,Hmax,Hstart, &
                         y,AbsTol,RelTol, &
                         Info)
      USE messy_scav_i_kpp_s_mem

!       L-stable Rosenbrock 3(2), with 
!     strongly A-stable embedded formula for error control.  
!
!     All the arguments aggree with the KPP syntax.
!
!  INPUT ARGUMENTS:
!     y = Vector of (NVAR) concentrations, contains the
!         initial values on input
!     [T, Tnext] = the integration interval
!     Hmin, Hmax = lower and upper bounds for the selected step-size.
!          Note that for Step = Hmin the current computed
!          solution is unconditionally accepted by the error
!          control mechanism.
!     AbsTol, RelTol = (NVAR) dimensional vectors of 
!          componentwise absolute and relative tolerances.
!     FUN = name of routine of derivatives. KPP syntax.
!          See the header below.
!     JAC_SP = name of routine that computes the Jacobian, in
!          sparse format. KPP syntax. See the header below.
!     Info(1) = 1  for  autonomous   system
!             = 0  for nonautonomous system 
!
!  OUTPUT ARGUMENTS:
!     y = the values of concentrations at Tend.
!     T = equals Tend on output.
!     Info(2) = # of FUN calls.
!     Info(3) = # of JAC_SP calls.
!     Info(4) = # of accepted steps.
!     Info(5) = # of rejected steps.
!    
!     Adrian Sandu, April 1996
!     The Center for Global and Regional Environmental Research

      IMPLICIT NONE !mz_rs_20030728

      ! mz_rs_20030728+
      REAL(dp) dround, gam, c21, c31, c32, b1, b2, b3, d1, d2, d3, a21
      REAL(dp) a31, a32, alpha2, alpha3, g1, g2, g3, tau, x1, x2, x3, ytol
      INTEGER    ier
      ! mz_rs_20030728-
      REAL(dp)     K1(NVAR), K2(NVAR), K3(NVAR)
      REAL(dp)     F1(NVAR), JAC(LU_NONZERO_V+1) ! mz_rs_20020604: 1 added
      REAL(dp)     Hmin,Hmax,Hstart,ghinv,uround
      REAL(dp)     y(NVAR), ynew(NVAR)
      REAL(dp)     AbsTol(NVAR), RelTol(NVAR)
      REAL(dp)     T, Tnext, H, Hold, Tplus
      REAL(dp)     ERR, factor, facmax
      INTEGER    n,nfcn,njac,Naccept,Nreject,i,j
      INTEGER    Info(5)
      LOGICAL    IsReject,Autonom
      ! EXTERNAL   FUN, JAC_SP

!     Initialization of counters, etc.
      Autonom = Info(1) .EQ. 1
      uround = 1.e-15
      dround = SQRT(uround)
      H = MAX(1.e-8_dp, Hstart) ! mz_rs_20040830: dp added
      Tplus = T
      IsReject = .false.
      Naccept  = 0
      Nreject  = 0
      Nfcn     = 0
      Njac     = 0
      gam=   .43586652150845899941601945119356e+00
      c21=  -.10156171083877702091975600115545e+01
      c31=   .40759956452537699824805835358067e+01
      c32=   .92076794298330791242156818474003e+01
       b1=   .10000000000000000000000000000000e+01
       b2=   .61697947043828245592553615689730e+01
       b3=  -.42772256543218573326238373806514e+00
       d1=   .50000000000000000000000000000000e+00
       d2=  -.29079558716805469821718236208017e+01
       d3=   .22354069897811569627360909276199e+00
       a21 = 1.e0
       a31 = 1.e0
       a32 = 0.e0
       alpha2 = gam
       alpha3 = gam
       g1=   .43586652150845899941601945119356e+00
       g2=   .24291996454816804366592249683314e+00
       g3=   .21851380027664058511513169485832e+01


! === Starting the time loop ===      
 10    continue  
       Tplus = T + H
       if ( Tplus .gt. Tnext ) then
          H = Tnext - T
          Tplus = Tnext
       end if

       call JAC_SP(NVAR, T, y, JAC)
       Njac = Njac+1
       gHinv = -1.0e0/(gam*H)
       do 15 j=1,LU_NONZERO_V
         JAC(j) = -JAC(j) 
 15    continue
       do 20 j=1,NVAR
         JAC(LU_DIAG_V(j)) = JAC(LU_DIAG_V(j)) - gHinv
 20    continue
       call DECOMP (NVAR, JAC, ier)

       if (ier.ne.0) then
         if ( H.gt.Hmin) then
            H = 5.0e-1*H
            go to 10
         else
            print *,'IER <> 0, H=',H
            stop
         end if      
       end if  
       
       call FUN(NVAR, T, y, F1)

! ====== NONAUTONOMOUS CASE ===============
       IF (.not. Autonom) THEN
         ! mz_rs_20040830: dp added to next line:
         tau = sign(dround*max( 1.0e-6_dp, abs(T) ), T)
         call FUN(NVAR, T+tau, y, K2)
         nfcn=nfcn+1
         do 30 j = 1,NVAR
           K3(j) = ( K2(j)-F1(j) )/tau
 30      continue
 
! ----- STAGE 1 (NONAUTONOMOUS) -----
         x1 = g1*H
         do 35 j = 1,NVAR
           K1(j) =  F1(j) + x1*K3(j)
 35      continue
         call SOLVE (JAC, K1)
      
! ----- STAGE 2 (NONAUTONOMOUS) -----
       do 40 j = 1,NVAR
         ynew(j) = y(j) + K1(j) 
 40    continue
       call FUN(NVAR, T+gam*H, ynew, F1)
       nfcn=nfcn+1
       x1 = c21/H
       x2 = g2*H
       do 45 j = 1,NVAR
         K2(j) = F1(j) + x1*K1(j) + x2*K3(j)
 45    continue
       call SOLVE (JAC, K2)
       
! ----- STAGE 3  (NONAUTONOMOUS) -----
       x1 = c31/H
       x2 = c32/H
       x3 = g3*H
       do 50 j = 1,NVAR
         K3(j) = F1(j) + x1*K1(j) + x2*K2(j) + x3*K3(j)
 50    continue
       call SOLVE (JAC, K3)


! ====== AUTONOMOUS CASE ===============
       ELSE

! ----- STAGE 1 (AUTONOMOUS) -----
         do 60 j = 1,NVAR
           K1(j) =  F1(j) 
 60      continue
         call SOLVE (JAC, K1)
      
! ----- STAGE 2 (AUTONOMOUS) -----
       do 65 j = 1,NVAR
         ynew(j) = y(j) + K1(j) 
 65    continue
       call FUN(NVAR, T + gam*H, ynew, F1)
       nfcn=nfcn+1
         x1 = c21/H
         do 70 j = 1,NVAR
           K2(j) = F1(j) + x1*K1(j) 
 70      continue
         call SOLVE (JAC, K2)
       
! ----- STAGE 3  (AUTONOMOUS) -----
       x1 = c31/H
       x2 = c32/H
       do 90 j = 1,NVAR
         K3(j) = F1(j) + x1*K1(j) + x2*K2(j)
 90    continue
       call SOLVE (JAC, K3)

       END  IF ! Autonomous

! ---- The Solution ---

       do 120 j = 1,NVAR
         ynew(j) = y(j) + b1*K1(j) + b2*K2(j) + b3*K3(j) 
 120   continue


! ====== Error estimation ========

        ERR=0.e0
        do 130 i=1,NVAR
           ytol = AbsTol(i) + RelTol(i)*abs(ynew(i))
           ERR=ERR+((d1*K1(i)+d2*K2(i)+d3*K3(i))/ytol)**2
 130    continue      
        ERR = MAX( uround, SQRT( ERR/NVAR ) )

! ======= Choose the stepsize ===============================

        factor = 0.9/ERR**(1.e0/3.e0)
        if (IsReject) then
            facmax=1.0
        else
            facmax=10.0
        end if 
        factor = MAX( 1.0e-1_dp, min(factor,facmax) ) ! mz_rs_20040830: dp added
        Hold = H
        H = min( Hmax, MAX(Hmin,factor*H) )    

! ======= Rejected/Accepted Step ============================

        if ( (ERR.gt.1).and.(Hold.gt.Hmin) ) then
          IsReject = .true.
          Nreject  = Nreject+1
          ! mz_ak_20060810+
          
          IF ((Nreject >INFO(5)) .AND. (INFO(5) > 0)) THEN
             Info(2) = Nfcn
             Info(3) = Njac
             Info(4) = Naccept
             Info(5) = Nreject
             RETURN
          ENDIF
          ! mz_ak_20060810-
        else
          IsReject = .false.
          do 140 i=1,NVAR
             y(i)  = ynew(i)
 140      continue 
          T = Tplus     
          Naccept = Naccept+1
        end if

! ======= End of the time loop ===============================
      if ( T .lt. Tnext ) go to 10
 
     
      
! ======= Output Information =================================
      Info(2) = Nfcn
      Info(3) = Njac
      Info(4) = Naccept
      Info(5) = Nreject
      
      END SUBROUTINE ROS3

  
  
        SUBROUTINE FUN(N, T, Y, P)
        USE messy_scav_i_kpp_g_mem
        IMPLICIT NONE !mz_rs_20030728
        INTEGER N !mz_rs_20030728
        REAL(dp)   T, Told
        REAL(dp)   Y(NVAR), P(NVAR)
        Told = TIME
        TIME = T
        CALL UPDATE_SUN()
        ! CALL UPDATE_PHOTO() ! mz_rs_20021113: subroutine call switched off
        CALL F_VAR( Y, RAD, P )
        TIME = Told
        END SUBROUTINE FUN

        SUBROUTINE JAC_SP(N, T, Y, J)
        USE messy_scav_i_kpp_g_mem
        IMPLICIT NONE !mz_rs_20030728
        INTEGER N !mz_rs_20030728
        REAL(dp)   Told, T
        REAL(dp)   Y(NVAR), J(LU_NONZERO_V+1) ! mz_rs_20020604: 1 added
        Told = TIME
        TIME = T
        CALL UPDATE_SUN()
        ! CALL UPDATE_PHOTO() ! mz_rs_20021113: subroutine call switched off
        CALL JACVAR_SP( Y, RAD, J )
        TIME = Told
        END SUBROUTINE JAC_SP
! End of INTEGRATE function                                        
! **************************************************************** 


END MODULE messy_scav_i_kpp

! User defined functions                                           

! End user defined functions                                       

! **************************************************************** 
!                                                                  
! MAIN - Main program - driver routine                             
!   Parameters :                                                   
!                                                                  
! **************************************************************** 

! just a dummy
! End of MAIN function                                             
! **************************************************************** 



! ****************************************************************************
! end of messy_scav_i_kpp.f90
! ****************************************************************************
