MODULE MESSY_ATTILA_MEM_E5

  USE messy_main_constants_mem, ONLY: dp

  PUBLIC
  SAVE

  INTRINSIC :: NULL
  PRIVATE NULL

  ! DIAGNOSTIC FIELDS IN ATTILA CHANNEL
  ! NUMBER OF CELLS PER GRID BOX (ALL CPUs) IN DECOMPOSITION
  REAL(dp), PUBLIC, DIMENSION(:,:,:), POINTER :: SGNCB   => NULL()
  REAL(dp), PUBLIC, DIMENSION(:,:,:), POINTER :: SGNCBM1 => NULL()

END MODULE MESSY_ATTILA_MEM_E5
