#! /bin/tcsh -f 
# -*- Shell-script -*- Time-stamp: <2018-07-02 18:24:41 sander>
# mmg = messy-multimodel-grep for MESSy2

# put the same find commands here as in etags command in Makefile.in!
# Fortran:
find . -name "*.f90"         -type f | xargs grep -iF "$1"
find . -name "*.f90-*"       -type f | xargs grep -iF "$1"
find . -name "*.inc"         -type f | xargs grep -iF "$1"
find . -name "*.nml"         -type f | xargs grep -iF "$1"
find . -name "*.f"           -type f | xargs grep -iF "$1" #  op_pj_20101118
find . -name "*.F"           -type f | xargs grep -iF "$1" #  op_pj_20101118
find . -name "*.F90"         -type f | xargs grep -iF "$1" #  op_pj_20170206
# Shell scripts:
find . -name "*.awk"         -type f | xargs grep -iF "$1"
find . -name "*.bash"        -type f | xargs grep -iF "$1"
find . -name "*.bat"         -type f | xargs grep -iF "$1"
find . -name "*.sh"          -type f | xargs grep -iF "$1"
find . -name "*.tcsh"        -type f | xargs grep -iF "$1"
find . -name "x*" -perm -100 -type f | xargs grep -iF "$1"
# KPP:
find . -name "*.eqn"         -type f | xargs grep -iF "$1"
find . -name "*.k"           -type f | xargs grep -iF "$1"
find . -name "*.kpp"         -type f | xargs grep -iF "$1"
find . -name "*.spc"         -type f | xargs grep -iF "$1"
find . -name "*.rpl"         -type f | xargs grep -iF "$1"
# Makefiles:
find . -name "*.mk"          -type f | xargs grep -iF "$1"
find . -name "Makefile.*"    -type f | xargs grep -iF "$1"
# Other:
find . -name "*.jnl"         -type f | xargs grep -iF "$1"
find . -name "*.tbl"         -type f | xargs grep -iF "$1"
find . -name "*.tex"         -type f | xargs grep -iF "$1"

find . -name "CHANGELOG"     -type f | xargs grep -iF "$1"

exit
