#! /bin/sh -e
############################################################################
##  script for modifing date and time of restart files of a MESSy simulation
##  by Andrea Pozzer (MPI-C) 
############################################################################
#  
script=`basename $0`
if [ $# -ne 1 ]; then
    echo "Use $script -h for more information!"
    exit 127
fi

case $1 in
  -h)
     echo "                                                         "
     echo "-------------------------------------------------------- "
     echo "  modify date and time in MESSy restart files            "
     echo "                                                         "
     echo "  USAGE:                                                 "
     echo "  $script [-h] <desired date>                            "
     echo "                                                         "
     echo "   -h : show this help and exit                          "
     echo "   desired date : new date (\"YYYYMMDD hhmmss\")         "
     echo "                                                         "
     echo "  Execute this script in the working directory after     "
     echo "  executing init_restart.                                "
     echo "---------------------------------------------------------"
     echo "                                                         "
     exit 0
esac 

echo " "

# check prerequisites
if which ncatted ; then
   echo "ncatted is present!"
else
   echo "problem with the nco ----> ncatted is missing!"
   exit 127
fi

if which ncrename ; then
   echo "ncrename is present!"
else
   echo "problem with the nco ----> ncrename is missing!"
   exit 127
fi

if which ncdump ; then
   echo "ncdump is present!"
else
   echo "problem with ncdump ----> ncdump is missing!"
   exit 127
fi

echo " "

############################ PROGRAM START ####################################

echo "************************************************************************"
echo "*                                                                      *"
echo "*              Modification of restart date / time for MESSy           *"
echo "*                                                                      *"
echo "*                  MPI-C, Andrea Pozzer, Aug 2009                      *"
echo "*                                                                      *"
echo "************************************************************************"
echo

new_start_date_time=`echo "$1" | tr -d '\0'`

echo " "
echo "new date / time is (YYYYMMDD hhmmss):" $new_start_date_time
echo " "

for file in restart_*.nc 
do
    echo $file

    ori=`ncdump -h $file | grep orig_nstep | wc -l`
    if [ $ori -eq 0 ] ; then
       mode=m
    else
       ncrename -O -a nstep,orig_nstep $file
       mode=c
    fi
    ncatted -O -a nstep,global,$mode,l,1 $file

    ori=`ncdump -h $file | grep orig_start_date_time | wc -l`
    if [ $ori -eq 0 ] ; then
       mode=m
    else
       ncrename -O -a start_date_time,orig_start_date_time $file
       mode=c
    fi
    ncatted -O -a start_date_time,global,$mode,c,"`echo "$1" | tr -d '\0'`" $file

    ori=`ncdump -h $file | grep orig_restart_date_time | wc -l`
    if [ $ori -eq 0 ] ; then
       mode=m
    else
       ncrename -O -a restart_date_time,orig_restart_date_time $file
       mode=c
    fi
    ncatted -O -a restart_date_time,global,$mode,c,"$new_start_date_time" $file

    ori=`ncdump -h $file | grep orig_GCM_start_date_time | wc -l`
    if [ $ori -eq 0 ] ; then
       mode=m
    else
       ncrename -O -a GCM_start_date_time,orig_GCM_start_date_time $file
       mode=c
    fi
    ncatted -O -a GCM_start_date_time,global,$mode,c,"$new_start_date_time" $file

    ncdump $file > tmp.txt
    rm $file
    sed -e 's/units =  ;/units = "" ;/g' -e  's/long_name =  ;/long_name = "" ;/g'  -e  's/aerosol_model =  ;/aerosol_model = ""  ;/g'  tmp.txt > tmp2.txt
    ncgen -o ${file} tmp2.txt 
    rm tmp.txt tmp2.txt

done

echo " "
echo '********************************************************'
echo '*** You need to modify restart_ncregrid.rst by hand. ***'
echo '********************************************************'
echo " "

exit 0

