#! /bin/tcsh -f 
# -*- Shell-script -*- Time-stamp: <2010-11-18 16:17:28 joec_pa>

if ( "$1" == "" ) then
  echo "smv = show MESSy version (for the directory structure of MESSy2)"
  echo "usage:"
  echo "  smv <emdir>"
  echo "  (<emdir> = ECHAM/MESSy directory)"
  echo "example:"
  echo "  smv messy_devel"
  exit
endif

if ( -d $1 ) then
  cd $1
  set current_version = `grep -i "modver *=" messy/smcl/messy_main_constants_mem.f90 | sed "s|.*'\(.*\)'.*|\1|g"`
  echo "`pwd` is based on MESSy version $current_version"
else
  echo "ERROR: directory $1 does not exist"
  exit 1
endif

exit
