#! /usr/bin/tcsh -f

# loop from 1 to 8
set interval=0
while ($interval<8)
  @ interval=$interval + 1
  mv br2.ef$interval                   Br2.ef$interval
  mv brcl.ef$interval                  BrCl.ef$interval
  mv brcl_not.ef$interval              BrCl_not.ef$interval
  mv brno2.ef$interval                 BrNO2.ef$interval
  mv brno3.ef$interval                 BrNO3.ef$interval
  mv bro.ef$interval                   BrO.ef$interval
  mv bro_not.ef$interval               BrO_not.ef$interval
  mv c3h7i.ef$interval                 C3H7I.ef$interval
  mv ccl4.ef$interval                  CCl4.ef$interval
  mv cf2cl2.ef$interval                CF2Cl2.ef$interval
  mv cf2clbr.ef$interval               CF2ClBr.ef$interval
  mv cfcl3.ef$interval                 CFCl3.ef$interval
  mv ch2br2.ef$interval                CH2Br2.ef$interval
  mv ch2clbr.ef$interval               CH2ClBr.ef$interval
  mv ch2cli.ef$interval                CH2ClI.ef$interval
  mv ch2i2.ef$interval                 CH2I2.ef$interval
  mv ch3br.ef$interval                 CH3Br.ef$interval
  mv ch3ccl3.ef$interval               CH3CCl3.ef$interval
  mv ch3cho.ef$interval                CH3CHO.ef$interval
  mv ch3cl.ef$interval                 CH3Cl.ef$interval
  mv ch3coch3.ef$interval              CH3COCH3.ef$interval
  mv ch3cocho.ef$interval              CH3COCHO.ef$interval
  mv ch3i.ef$interval                  CH3I.ef$interval
  mv ch3ooh.ef$interval                CH3OOH.ef$interval
  mv ch4_co.ef$interval                CH4_CO.ef$interval
  mv chbr3.ef$interval                 CHBr3.ef$interval
  mv chcl2br.ef$interval               CHCl2Br.ef$interval
  mv chclbr2.ef$interval               CHClBr2.ef$interval
  mv choh.ef$interval                  CHOH.ef$interval
  mv cl2.ef$interval                   Cl2.ef$interval
  mv cl2o2.ef$interval                 Cl2O2.ef$interval
  mv clno2.ef$interval                 ClNO2.ef$interval
  mv clno3.ef$interval                 ClNO3.ef$interval
  mv co2.ef$interval                   CO2.ef$interval
  mv coh2.ef$interval                  COH2.ef$interval
  mv h2o2.ef$interval                  H2O2.ef$interval
  mv h2o.ef$interval                   H2O.ef$interval
  mv hcl.ef$interval                   HCl.ef$interval
  mv h_no2.ef$interval                 h_NO2.ef$interval
  mv hno3.ef$interval                  HNO3.ef$interval
  mv hno4.ef$interval                  HNO4.ef$interval
  mv h_o2.ef$interval                  h_O2.ef$interval
  mv h_o3.ef$interval                  h_O3.ef$interval
  mv h_o4.ef$interval                  h_O4.ef$interval
  mv hobr.ef$interval                  HOBr.ef$interval
  mv hocl.ef$interval                  HOCl.ef$interval
  mv hoi.ef$interval                   HOI.ef$interval
  mv hono.ef$interval                  HONO.ef$interval
  mv i2.ef$interval                    I2.ef$interval
  mv ibr.ef$interval                   IBr.ef$interval
  mv icl.ef$interval                   ICl.ef$interval
  mv ino2.ef$interval                  INO2.ef$interval
  mv ino3.ef$interval                  INO3.ef$interval
  mv io.ef$interval                    IO.ef$interval
  mv n2o5.ef$interval                  N2O5.ef$interval
  mv n2o.ef$interval                   N2O.ef$interval
  mv no2.ef$interval                   NO2.ef$interval
  mv no2o.ef$interval                  NO2O.ef$interval
  mv noo2.ef$interval                  NOO2.ef$interval
  mv o1d.ef$interval                   O1D.ef$interval
  mv o2.ef$interval                    O2.ef$interval
  mv o3.ef$interval                    O3.ef$interval
  mv o3p.ef$interval                   O3P.ef$interval
  mv oclo.ef$interval                  OClO.ef$interval
  mv oclo_not.ef$interval              OClO_not.ef$interval
end

exit
