
#include "messy_mecca_tag_parameters.inc"

#define xNMHC_EMIS
#define xOFFLEMB
#define xEXP_PM_TANS
#define xISO_STRAT
#define  ISO_TROP             // initialise typical tropospheric composition

#define xDEBUG
#define xDEEPDEBUG

#define xCIO_YEUNG_EXP        // flag for messy_mecca_box that we simulate Yeung's experiment
#define xCIO_ATOMTR_TEST      // flag for messy_mecca_box that we test ATOM-TR kinetics

#define xEXP_STOZ
