#! /bin/sh
cat <<EOF
  WRITE (io_unit, '(A)') &
       "Compile time options (pre-processor keys): ", &
EOF
while read key files
do
  echo '#ifdef '"$key"
  echo "   \"$key\", &"
  echo '#endif'
done
cat <<EOF
       ""
EOF
