#! /bin/sh
WORKING_DIR=.
if [ "$1" ]
then
    WORKING_DIR=$1
fi

trap 'echo $INFO' 0

INFO=`svnversion $WORKING_DIR`
[ "$INFO" -a "$INFO" != exported ] && exit

# Git support needs to be tested!
# INFO=`cd $WORKING_DIR > /dev/null && git log -1 --format='$H'`
# [ "$INFO" ] && exit

INFO=unknown
