#! /bin/tcsh -f
# Time-stamp: <2013-03-13 11:11:53 sander>
# xjval: eXecute jval

##############################################################################

echo
echo "Compile f90 files? [y|n|q, default=y]"
set inputstring = "$<"
if ( "$inputstring" == "q" ) exit 1
if ( "$inputstring" != "n" ) then
  gmake
endif

##############################################################################

echo
echo "Run jval.exe? [y|n|q, default=y]"
set inputstring = "$<"
if ( "$inputstring" == "q" ) exit 1
if ( "$inputstring" != "n" ) then
    ./jval.exe | & tee jval.log
endif

##############################################################################

exit

##############################################################################
