#! /bin/tcsh -f

set texfile = caaba_mecca_manual.tex

#set timestamp=`date +"%Y-%m-%d-%H-%M-%S"`
#set tmpfile1 = tmp_${timestamp}_1

# some code based on ~/bin/wordlist:
sed 's/\\_/_/g' $texfile | \
  tr -cs '_A-Za-z0-9-' '\012' | \
  sort -df | \
  uniq | \
  sed 's/.*/(query-replace "&" "\\indexthis{&}" nil)/g' > wordlist.txt

#(query-replace "old" "new" nil)


# cleanup:
# rm $tmpfile1 $tmpfile2 $tmpfile3
# rm tmp_*

exit
