# -*- Makefile -*-
# ----------------------------------------------
export
SHELL    = sh

F90       = lf95
F90FLAGS  = --f95 --chk a,e,s,u -Cpp
LIBS      = -L/soft/netcdf/v3.6.0b6_lf/lib -lnetcdf
INCLUDES  = -I/soft/netcdf/v3.6.0b6_lf/include

INSTALLDIR = .
# ----------------------------------------------
include main.mk
# ----------------------------------------------
