#! /bin/tcsh -f
# Time-stamp: <2016-09-27 11:49:59 sander>
# xcloudj: eXecute cloudj

##############################################################################

echo
echo "Compile f90 files? [y|n|q, default=y]"
set inputstring = "$<"
if ( "$inputstring" == "q" ) exit 1
if ( "$inputstring" != "n" ) then
  gmake
endif

##############################################################################

echo
echo "Run cloudj.exe? [y|n|q, default=y]"
set inputstring = "$<"
if ( "$inputstring" == "q" ) exit 1
if ( "$inputstring" != "n" ) then
    ./cloudj.exe | & tee cloudj.log
endif

##############################################################################

exit

##############################################################################
